import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navber from "@/components/shared/Navber";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sharmin portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Load the anime.min.js script */}
        <Script src="/path/to/anime.min.js" strategy="lazyOnload" />
        
        <Navber />
        <div className="w-full bg-gradient-to-r from-[#001f3f] via-[#000000] to-[#511592]">{children}</div>
      </body>
    </html>
  );
}
